### ISSUE TITLE
DIME Analytics team feedback

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/r-econ-visual-library#8]
- [x] Data Visualization Cheatsheet (found here) is different then others
- [x] Fix "about us" to department
- [ ] Have an outline of graphs in each page
- [x] Explain what the graphs in the landing page are
- [x] Improve spacing between graphs

**Comment by mariaruth** [comment]
can we change the 'useful links' section so that it is distinguishable from summary statistics and impact evaluation? right now it looks like it would be the same type of category. maybe we could move it to run along the bottom, above 'about us'? or change the formatting so it is more clearly distinct

**Comment by MichaelBeeli** [comment]
Develop Branch: 

1) "EventStudyDinD" Y and X labels are flipped, relative to the website 
https://github.com/worldbank/r-econ-visual-library/blob/b64f0c3c4025c4c3c84e0d293c8005e0448c3476/Library/EventStudyDinD.Rmd#L94-L97

2) "ScatterFittedLine" Y and X labels are flipped, relative to the website 
https://github.com/worldbank/r-econ-visual-library/blob/b64f0c3c4025c4c3c84e0d293c8005e0448c3476/Library/ScatterFittedLine.Rmd#L42-L45

3) Data not found for: "Scatterlabels", "HorizontalBarOrderGroup"
